apiVersion: v1
kind: Service
metadata:
  name: unleash
  namespace: feature-flags
  labels:
    app: unleash
spec:
  selector:
    app: unleash
  ports:
    - name: http
      port: 4242
      targetPort: 4242
  type: ClusterIP
