apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: ghcr.io/org/acme-api
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: staging
    target:
      kind: ConfigMap
      name: acme-api-config
